project: 
  type: website
  render: 
    - index.qmd
    - content/teaching.qmd
    - content/talks.qmd
    - content/codes.qmd

website: 
  back-to-top-navigation: true
  page-navigation: true
  search: false
  title: AS
  navbar: 
    left:
     - text: Home
       href: index.qmd
     - text: Teaching
       href: content/teaching.qmd
     - text: Talks
       href: content/talks.qmd
     #- text: CV
     - text: Code
       href: content/codes.qmd
  #sidebar: 
    #logo: Photo_CV.jpg
    #logo-alt: "CV photo"
format: 
  html: 
    theme: flatly
    #css: styles.css
    toc: true